<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ZfcUserCrud\Module'                    => __DIR__ . '/Module.php',
  'ZfcUserCrud\Controller\CrudController' => __DIR__ . '/src/ZfcUserCrud/Controller/CrudController.php',
  'ZfcUserCrud\Controller\RoleController' => __DIR__ . '/src/ZfcUserCrud/Controller/RoleController.php',
  'ZfcUserCrud\Entity\Role'               => __DIR__ . '/src/ZfcUserCrud/Entity/Role.php',
  'ZfcUserCrud\Entity\User'               => __DIR__ . '/src/ZfcUserCrud/Entity/User.php',
);
